# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 720)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 141, 51))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 0, 801, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 10, 371, 51))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setGeometry(QtCore.QRect(160, 220, 391, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 120, 141, 51))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 141, 51))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 240, 141, 51))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 300, 141, 51))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        self.pushButton.clicked.connect(Dialog.click_index_0) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.click_index_1) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.click_index_2) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.click_index_3) # type: ignore
        self.pushButton_6.clicked.connect(Dialog.click_index_4) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.addcsv) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "主页"))
        self.pushButton_3.setText(_translate("Dialog", "点击添加数据"))
        self.pushButton_2.setText(_translate("Dialog", "数据处理"))
        self.pushButton_4.setText(_translate("Dialog", "2"))
        self.pushButton_5.setText(_translate("Dialog", "3"))
        self.pushButton_6.setText(_translate("Dialog", "4"))
