# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 720)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 141, 51))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 0, 850, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.widget = QtWidgets.QWidget(self.page_0)
        self.widget.setGeometry(QtCore.QRect(110, 60, 661, 401))
        self.widget.setObjectName("widget")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 490, 141, 51))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_9.setGeometry(QtCore.QRect(430, 490, 141, 51))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 10, 371, 51))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setGeometry(QtCore.QRect(90, 80, 721, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(70, 60, 381, 291))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.label_24 = QtWidgets.QLabel(self.page_2)
        self.label_24.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lineEdit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit.setGeometry(QtCore.QRect(130, 80, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 160, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 120, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit.setGeometry(QtCore.QRect(130, 210, 181, 21))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(130, 240, 181, 21))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 40, 181, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setGeometry(QtCore.QRect(10, 240, 71, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setGeometry(QtCore.QRect(0, 120, 71, 21))
        self.label_23.setObjectName("label_23")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 280, 101, 31))
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 40, 181, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 120, 181, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_5.setGeometry(QtCore.QRect(130, 210, 181, 21))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.dateEdit_6 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_6.setGeometry(QtCore.QRect(130, 240, 181, 21))
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 80, 181, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 160, 181, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(10, 240, 71, 21))
        self.label_11.setObjectName("label_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 280, 101, 31))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.stackedWidget.addWidget(self.page_4)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 120, 141, 51))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 141, 51))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 240, 141, 51))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 300, 141, 51))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(Dialog.click_index_0) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.click_index_1) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.click_index_2) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.click_index_3) # type: ignore
        self.pushButton_6.clicked.connect(Dialog.click_index_4) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.addcsv) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "主页"))
        self.pushButton_8.setText(_translate("Dialog", "加载充电站数据"))
        self.pushButton_9.setText(_translate("Dialog", "手动标记"))
        self.pushButton_3.setText(_translate("Dialog", "点击添加数据"))
        self.label_24.setText(_translate("Dialog", "计数分析"))
        self.label_18.setText(_translate("Dialog", "模型选择"))
        self.label_19.setText(_translate("Dialog", "充电桩编号"))
        self.label_20.setText(_translate("Dialog", "开始时间"))
        self.label_21.setText(_translate("Dialog", "充电站编号"))
        self.label_22.setText(_translate("Dialog", "结束时间"))
        self.label_23.setText(_translate("Dialog", "故障种类编号"))
        self.pushButton_10.setText(_translate("Dialog", "提交"))
        self.label.setText(_translate("Dialog", "充电站编号"))
        self.label_2.setText(_translate("Dialog", "充电桩编号"))
        self.label_3.setText(_translate("Dialog", "故障种类编号"))
        self.label_4.setText(_translate("Dialog", "模型选择"))
        self.label_5.setText(_translate("Dialog", "开始时间"))
        self.label_11.setText(_translate("Dialog", "结束时间"))
        self.pushButton_11.setText(_translate("Dialog", "提交"))
        self.pushButton_2.setText(_translate("Dialog", "数据处理"))
        self.pushButton_4.setText(_translate("Dialog", "数据展示"))
        self.pushButton_5.setText(_translate("Dialog", "故障诊断"))
        self.pushButton_6.setText(_translate("Dialog", "故障预警"))
