# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v6.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1027, 726)
        self.gridLayout_9 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_13.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_13.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_13.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("background-color:rgb(38, 104, 191);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_13.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_0)
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("background-color:rgb(0, 26, 65);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.page_0)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_1)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("background-color:rgb(0, 26, 65);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_11.addWidget(self.pushButton_3, 0, 0, 1, 1)
        # add a status bar
        self.progressBar=QtWidgets.QProgressBar(self.page_1)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(0)

        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget, 1, 0, 1, 1)
        ## vertically below the tablewidget
        self.gridLayout_11.addWidget(self.progressBar, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_2_3 = QtWidgets.QWidget(self.page_2)
        self.widget_2_3.setObjectName("widget_2_3")
        self.widget_2_1_zoom_out = True
        self.widget_2_2_zoom_out = True
        self.widget_2_3_zoom_out = True
        self.widget_2_4_zoom_out = True
        self.gridLayout_12.addWidget(self.widget_2_3, 1, 0, 1, 3)
        self.widget_2_4 = QtWidgets.QWidget(self.page_2)
        self.widget_2_4.setObjectName("widget_2_4")
        self.gridLayout_12.addWidget(self.widget_2_4, 1, 3, 1, 2)
        self.widget_2_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2_2.setObjectName("widget_2_2")
        self.gridLayout_12.addWidget(self.widget_2_2, 0, 3, 1, 2)
        self.widget_2_1 = QtWidgets.QWidget(self.page_2)
        self.widget_2_1.setObjectName("widget_2_1")
        self.gridLayout_12.addWidget(self.widget_2_1, 0, 0, 1, 3)
        self.gridLayout_12.setColumnStretch(0, 1)
        self.gridLayout_12.setColumnStretch(1, 1)
        self.gridLayout_12.setColumnStretch(2, 1)
        self.gridLayout_12.setColumnStretch(3, 1)
        self.gridLayout_12.setColumnStretch(4, 1)
        self.gridLayout_12.setRowStretch(0, 1)
        self.gridLayout_12.setRowStretch(1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.gridLayout_6.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_20.setStyleSheet("background-color:rgb(0, 26, 65);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_6.addWidget(self.pushButton_20, 1, 1, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.comboBox_Station = QtWidgets.QComboBox(self.page_3)
        self.comboBox_Station.setObjectName("comboBox_Station")
        self.verticalLayout_12.addWidget(self.comboBox_Station)
        self.comboBoxFault = QtWidgets.QComboBox(self.page_3)
        self.comboBoxFault.setObjectName("comboBoxFault")
        for i in range(0, 7):
            self.comboBoxFault.addItem("")
        self.verticalLayout_12.addWidget(self.comboBoxFault)
        self.comboBox_6 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_12.addWidget(self.comboBox_6)
        self.dateEdit = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 9, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_12.addWidget(self.dateEdit)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_12.addWidget(self.dateEdit_2)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.widget_3_3 = QtWidgets.QWidget(self.page_3)
        self.widget_3_3.setObjectName("widget_3_3")
        self.gridLayout_14.addWidget(self.widget_3_3, 0, 1, 1, 1)
        self.widget_3_1 = QtWidgets.QWidget(self.page_3)
        self.widget_3_1.setObjectName("widget_3_1")
        self.gridLayout_14.addWidget(self.widget_3_1, 1, 0, 1, 1)
        self.widget_3_2 = QtWidgets.QWidget(self.page_3)
        self.widget_3_2.setObjectName("widget_3_2")
        self.gridLayout_14.addWidget(self.widget_3_2, 1, 1, 1, 1)
        self.gridLayout_14.setColumnStretch(0, 1)
        self.gridLayout_14.setColumnStretch(1, 1)
        self.gridLayout_14.setRowStretch(0, 1)
        self.gridLayout_14.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_station = QtWidgets.QLabel(self.page_4)
        self.label_station.setObjectName("label_station")
        self.verticalLayout.addWidget(self.label_station)
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet("background-color:rgb(0, 26, 65);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"等线\";\n"
"\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.lineEdit_5 = QtWidgets.QLineEdit(self.page_4)
        # self.lineEdit_5.setObjectName("lineEdit_5")
        # self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.comboBox_Station_II = QtWidgets.QComboBox(self.page_4)
        self.comboBox_Station_II.setObjectName("comboBox_Station_II")
        self.verticalLayout_2.addWidget(self.comboBox_Station_II)
        self.comboBox = QtWidgets.QComboBox(self.page_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        # self.lineEdit_9 = QtWidgets.QLineEdit(self.page_4)
        # self.lineEdit_9.setObjectName("lineEdit_9")
        # self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.spinBox = QtWidgets.QSpinBox(self.page_4)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMaximum(24*30)
        self.spinBox.setMinimum(0)
        self.spinBox.setSingleStep(6)
        self.spinBox.setValue(24)
        self.verticalLayout_2.addWidget(self.spinBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.widget_4_2 = QtWidgets.QWidget(self.page_4)
        self.widget_4_2.setObjectName("widget_4_2")
        self.gridLayout_15.addWidget(self.widget_4_2, 0, 1, 1, 1)
        self.widget_4_1 = QtWidgets.QWidget(self.page_4)
        self.widget_4_1.setObjectName("widget_4_1")
        self.gridLayout_15.addWidget(self.widget_4_1, 1, 0, 1, 1)
        self.widget_4_3 = QtWidgets.QWidget(self.page_4)
        self.widget_4_3.setObjectName("widget_4_3")
        self.gridLayout_15.addWidget(self.widget_4_3, 1, 1, 1, 1)
        self.gridLayout_15.setColumnStretch(0, 1)
        self.gridLayout_15.setColumnStretch(1, 1)
        self.gridLayout_15.setRowStretch(0, 1)
        self.gridLayout_15.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 8)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(4)
        self.pushButton_2.clicked.connect(Dialog.click_index_1) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.click_index_3) # type: ignore
        self.pushButton_6.clicked.connect(Dialog.click_index_4) # type: ignore
        self.pushButton.clicked.connect(Dialog.click_index_0) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.click_index_2) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.addcsv) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "主页"))
        self.pushButton_2.setText(_translate("Dialog", "数据处理"))
        self.pushButton_4.setText(_translate("Dialog", "数据展示"))
        self.pushButton_5.setText(_translate("Dialog", "故障诊断"))
        self.pushButton_6.setText(_translate("Dialog", "故障预警"))
        self.pushButton_8.setText(_translate("Dialog", "加载充电站数据"))
        self.pushButton_3.setText(_translate("Dialog", "点击添加数据并进行处理"))
        self.label_16.setText(_translate("Dialog", "充电站编号"))
        self.label_3.setText(_translate("Dialog", "故障类型"))
        self.label_17.setText(_translate("Dialog", "模型选择"))
        self.label_6.setText(_translate("Dialog", "开始时间"))
        self.label_7.setText(_translate("Dialog", "结束时间"))
        self.pushButton_20.setText(_translate("Dialog", "提交"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "XGBoost"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "RFforest"))

        self.label_station.setText(_translate("Dialog", "充电站编号"))
        self.label_4.setText(_translate("Dialog", "模型选择"))
        self.label_5.setText(_translate("Dialog", "预警时间"))
        self.pushButton_11.setText(_translate("Dialog", "提交"))
        self.comboBox.setItemText(0, _translate("Dialog", "XGBoost"))
        self.comboBox.setItemText(1, _translate("Dialog", "RFforest"))
        self.comboBox.setItemText(2, _translate("Dialog", "LGBM"))

        self.comboBoxFault.setItemText(0, _translate("Dialog", "voltage_fault_1"))
        self.comboBoxFault.setItemText(1, _translate("Dialog", "voltage_fault_2"))
        self.comboBoxFault.setItemText(2, _translate("Dialog", "voltage_fault_3"))
        self.comboBoxFault.setItemText(3, _translate("Dialog", "current_fault_1"))
        self.comboBoxFault.setItemText(4, _translate("Dialog", "current_fault_2"))
        self.comboBoxFault.setItemText(5, _translate("Dialog", "temperature_fault_1"))
        self.comboBoxFault.setItemText(6, _translate("Dialog", "temperature_fault_2"))
        self.comboBox_Station.setItemText(0, _translate("Dialog", "1"))
